[package]
name = "displaycfg"
version = "0.1.0"
authors = ["Michael Craggs <m.e.craggs@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

